[logs]
[logs.logs]
[logs.logs.start_date]
update_type = 1
new_type = "string"
new_name = "start_date"
default = "CURRENT_TIMESTAMP"

[logs.logs.date]
update_type = 2
new_type = "string"
new_name = "end_date"
default = "CURRENT_TIMESTAMP"
