// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthenticateWithTwitch():Promise<main.AccessTokenResponse>;

export function GetCurrentUsername():Promise<main.GetCurrentUsernameResponse>;

export function GetGamesById(arg1:Array<number>,arg2:string):Promise<main.GetGamesByIdResponse>;

export function GetRandomGames(arg1:number,arg2:string):Promise<main.GetRandomGamesResponse>;

export function GetSimilarGames(arg1:Array<number>,arg2:string):Promise<main.GetSimilarGamesResponse>;

export function OpenDirectoryDialog():Promise<main.OpenDirectoryDialogResponse>;

export function SearchForGame(arg1:string,arg2:string):Promise<main.SearchForGameResponse>;
