// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateWithTwitch() {
  return window['go']['main']['App']['AuthenticateWithTwitch']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SearchForGame(arg1, arg2) {
  return window['go']['main']['App']['SearchForGame'](arg1, arg2);
}
