// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateWithTwitch() {
  return window['go']['main']['App']['AuthenticateWithTwitch']();
}

export function GetCurrentUsername() {
  return window['go']['main']['App']['GetCurrentUsername']();
}

export function GetGamesById(arg1, arg2) {
  return window['go']['main']['App']['GetGamesById'](arg1, arg2);
}

export function GetRandomGames(arg1, arg2) {
  return window['go']['main']['App']['GetRandomGames'](arg1, arg2);
}

export function GetSimilarGames(arg1, arg2) {
  return window['go']['main']['App']['GetSimilarGames'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SearchForGame(arg1, arg2) {
  return window['go']['main']['App']['SearchForGame'](arg1, arg2);
}
