// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthenticateWithTwitch():Promise<main.AccessTokenResponse>;

export function DeleteLog(arg1:number):Promise<string>;

export function GetCurrentUsername():Promise<main.GetCurrentUsernameResponse>;

export function GetDashboardStatistics():Promise<main.GetDashboardStatisticsResponse>;

export function GetGameLogs(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<main.Log>>;

export function GetGamesById(arg1:Array<number>,arg2:string):Promise<main.GetGamesByIdResponse>;

export function GetLogById(arg1:number):Promise<main.GetLogByIdResponse>;

export function GetRandomGames(arg1:number,arg2:string):Promise<main.GetRandomGamesResponse>;

export function GetRecentLogs(arg1:number,arg2:Array<string>):Promise<main.GetRecentLogsResponse>;

export function GetSimilarGames(arg1:Array<number>,arg2:string):Promise<main.GetSimilarGamesResponse>;

export function GetUserSettings():Promise<main.GetUserSettingsResponse>;

export function InsertExecutableDetails(arg1:main.ExecutableDetails):Promise<main.InsertExecutableDetailsResponse>;

export function InsertGameLog(arg1:main.LogData):Promise<main.InsertGameLogResponse>;

export function OpenDirectoryDialog():Promise<main.OpenDirectoryDialogResponse>;

export function SaveUserSettings(arg1:main.UserSettingsData):Promise<void>;

export function SearchForGame(arg1:string,arg2:string):Promise<main.SearchForGameResponse>;

export function UpdateLog(arg1:number,arg2:main.LogData):Promise<string>;
