// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthenticateWithTwitch():Promise<main.AccessTokenResponse>;

export function GetRandomGames(arg1:number,arg2:string):Promise<main.GetRandomGamesResponse>;

export function OpenDirectoryDialog():Promise<main.OpenDirectoryDialogResponse>;

export function SearchForGame(arg1:string,arg2:string):Promise<main.SearchForGameResponse>;
