// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameLogs(arg1, arg2, arg3) {
  return window['go']['main']['Database']['GetGameLogs'](arg1, arg2, arg3);
}

export function InsertGameLog(arg1) {
  return window['go']['main']['Database']['InsertGameLog'](arg1);
}
