// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllGameLogs():Promise<Array<main.Log>>;

export function InsertGameLog(arg1:main.LogData):Promise<main.Log>;
