// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDashboardStatistics():Promise<main.GetDashboardStatisticsResponse>;

export function GetGameLogs(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<main.Log>>;

export function GetRecentLogs(arg1:number):Promise<main.GetRecentLogsResponse>;

export function GetUserSettings():Promise<main.GetUserSettingsResponse>;

export function InsertExecutableDetails(arg1:main.ExecutableDetails):Promise<main.InsertExecutableDetailsResponse>;

export function InsertGameLog(arg1:main.LogData):Promise<main.InsertGameLogResponse>;

export function SaveUserSettings(arg1:main.UserSettingsData):Promise<void>;
