// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllGameLogs() {
  return window['go']['main']['Database']['GetAllGameLogs']();
}

export function InsertGameLog(arg1) {
  return window['go']['main']['Database']['InsertGameLog'](arg1);
}
